### PR TITLE
update shoptab item property to be a string

### PR DESCRIPTION
**Pull request by baughj**
This corrects a defect where we made the shoptab a `byte`, when in fact it needs to be a `string` (which is what the client expects in metafiles).

This looks like a big PR because i reformatted the xsd to look nice, but in reality only one thing has changed.

### CODE REVIEW

**Comment by Fluffguck** [comment]
👍
https://hybrasyl.atlassian.net/browse/SERVER-204

**Comment by baughj** [comment]
@norrismiv Please review when convenient.

**Comment by norrismiv** [comment]
ShopTab was a byte, as that was what was returned by the server. However, it appears that data is not used.

**Comment by baughj** [comment]
`ShopTab` is a string, that was confirmed by @kojasou .

**Comment by norrismiv** [comment]
That's fine. I'm not arguing it. Just stating why it was a byte previously.

**Pull request merged**
