### PR TITLE
[SERVER-226] Can't click Next and go to top level menu

### PR DESCRIPTION
**Pull request by baughj**
## Description
This PR fixes the issue where clicking `next` from a dialog will not advance back to the main menu.

## Related PRs
n/a

## Checklist
- [x] Tested and working locally
- [ ] Reviewed
- [ ] Tested and working on dev server
- [ ] Deployed to staging

## How to QA
Talk to an NPC, open a dialog sequence; click next through it - ensure that at the end of the sequence, hitting next returns to the main menu.

## Impacted Areas in Hybrasyl
Dialogs.

### CODE REVIEW

**Comment by baughj** [comment]
@norrismiv Please review when convenient.

**Comment by norrismiv** [comment]
Does this account for also having the ability to have `Next` exiting the menu as well? This should be configurable, depending on the scenario.

**Comment by baughj** [comment]
No. I will add that.

**Comment by norrismiv** [comment]
Ok.

**Comment by baughj** [comment]
This has been addressed by making it an option `CloseOnEnd` for `DialogSequence`, which will default to false (go back to main menu).

**Comment by norrismiv** [comment]
👍

**Pull request merged**
