### PR TITLE
Supporting negative weights

### PR DESCRIPTION
**Pull request by luke-segars**
See bug at https://hybrasyl.atlassian.net/browse/SERVER-69.

This patch modifies how inventory weight is stored to support negative weights. Mark's diagnosis in the bug was correct; previously weight was being stored as an unsigned integer (meaning no negatives and it'd wrap around to a gigantic value if you tried).

Not a lot of notable changes here, but one explicit design decision work mentioning. I separated Inventory.CurrentWeight into two different properties: CurrentWeight (the true weight of the inventory, which could be negative), and VisibleWeight (which is never less than zero, intended to be displayed to the client). This introduces potential for bugs down the road since there are two ways to access the weight, though IMO this is the "right" way to do it since it allows for properly accounting for circumstances where the user goes from a negative weight to a positive weight (properly discounting the negative weight). For example, if you pick up items in the following order with the following weights:

[With single field] 1 + 1 - 2 - 2 + 1 = 1, since you effectively forget about everything < 0

[With two fields] 1 + 1 - 2 - 2 + 1 = -1, though displayed to the client as zero

I tested this by creating two items, one having positive weight and the other having negative. I've confirmed that items with negative weights can now be picked up, that they have the intended effect on the full inventory weight, and that picking up various sequences like the one shown above produce the proper values.

### CODE REVIEW

**Comment by luke-segars** [comment]
One quick note on the potential for bugs w/ this approach is that I think the risk should be fairly low; you basically always want to use CurrentWeight unless you're sending data to the frontend, in which case you should use VisibleWeight. From what I can tell the cases where you're sending inventory weight to the frontend are pretty well-contained.

Feedback welcome!

**Comment by luke-segars** [comment]
I've read and agree to the contributor agreement published at https://github.com/hybrasyl/server/blob/master/CONTRIBUTING.md..

**Comment by luke-segars** [comment]
Just noticing that I should probably make this change for equipment too (it's currently only done for inventory). Will try to revise this weekend.

**Comment by luke-segars** [comment]
Actually, I take it back. Creature.Inventory and Creature.Equipment are both instances of Inventory, which should properly support negative weights, meaning that if you equip something with a weight of -1 you should be able to carry 1 unit more than you could before. I think this is good to go.

**Comment by baughj** [comment]
Hi Luke, sorry I didn't see this, apparently I need to better manage notifications. In the future, feel free to ping the dev list about PRs.

I think these changes are good, except they seem to have a lot of crufty history from your other branch. Do you mind squashing everything that doesn't belong exclusively to this PR?

**Comment by luke-segars** [comment]
I'm actually gonna clean this up and reopen as a new PL. Lots of extra early learning junk in here at the moment.

**Pull request closed without merging**
