### PR TITLE
Serverside support for changing passwords

### PR DESCRIPTION
**Pull request by luke-segars**
See bug at https://hybrasyl.atlassian.net/browse/SERVER-115.

This PL provides a serverside implementation for password changing. It also refactors some of the existing account creation code into a small set of functions in order to ensure that the process used to hash, verify, and validate passwords is consistent across the account creation and password change flows.

Note that I'm using context clues to figure out what I should be passing as the `type` value to `LoginMessage`. I tested it and it works so I'm assuming it's fine ;-)

Comments welcome!

### CODE REVIEW

**Comment by kojasou** [comment]
What a coincidence, I was just dealing with passwords in another project myself! Here are some results I found.

Error code | Error message | Details / Example
-----------|---------------|-----------------
`0x00` | Changed successfully | Self-explanatory
`0x05`<sup>1</sup> | The password must be between 4 and 8 characters. | Self-explanatory
`0x07`<sup>1</sup> | That numeric password is too short. | Numeric password less than 6 characters (e.g. 12345)
`0x08`<sup>1</sup> | That password is too simple. | Password is a repeated character (e.g. aaaaaa, 11111)
`0x09`<sup>1</sup> | That password has invalid characters. | USDA requires alphanumeric passwords. Yep.
`0x0A`<sup>1</sup> | That password is too easy to guess. | Password is a sequence (e.g. abcdef, 123456)
`0x0E`<sup>1</sup> | That name does not exist. | Self-explanatory
`0x0F`<sup>2</sup> | Incorrect password | Self-explanatory

Error code would be the `type` value in the `LoginMesage` method.

<sup>1</sup> These errors clear and focus the "New password" field (yes, non-existent name as well.)
<sup>2</sup> These errors clear and focus the "Password" field.

**Comment by luke-segars** [comment]
That's a 90's set of password validation rules right there ;-) thanks Kyle, this is great.

@baughj and @kojasou, I'll see if I can integrate this info later this week before you roll it in.

**Comment by baughj** [comment]
Thanks! This looks good. About the only other changes I would suggest is to log failed password change attempts at an error level, successful changes at info, and attempts for invalid players either at debug or error.

Thanks for the packet grinding info as always, @kojasou.

**Comment by luke-segars** [comment]
I think rebasing may have broken things here, going to have to play around with that. Anyway, I refactored things a bit to incorporate both of your suggestions; the client should now we receiving the error codes it expects for the conditions @kojasou provided above, and logging is done at the levels suggested by @baughj.

**Comment by luke-segars** [comment]
Rebased and ready for review. Thanks!

**Comment by baughj** [comment]
OK......we need to have a talk in the future about rebasing / branching, because this branch history is seriously AFU. Squashed / merged by hand.

**Comment by baughj** [comment]
Hm....aaaand apparently I still messed that up. Cool! Well, closing, since this is actually merged, even if Github doesn't believe me.

**Pull request closed without merging**
