### PR TITLE
Fix current/max level display for castables

### PR DESCRIPTION
**Pull request by kojasou**
This fixes the AddSkill and AddSpell packets to properly display the current and maximum level for castables based on the player's class and master status. It also adds a convenient method to the User class for getting the maximum level of a castable based on the aforementioned variables.

### CODE REVIEW

**Comment by norrismiv** [comment]
neat, but couldn't GetCastableMaxLevel be simplified to the following? 
`public int GetCastableMaxLevel(Castable castable)
        {
            if (IsMaster)
            {
                return 100;
            }

            var propertyInfo = castable.MaxLevel.GetType().GetProperty(Class.ToString());
            if (propertyInfo != null)
                return (int)(propertyInfo.GetValue(castable.MaxLevel, null));
        }`

**Comment by baughj** [comment]
I thought about this too - and even suggested it to @kojasou - but do we really want reflection versus a case statement? We end up making every call to it much slower just to save five or six lines.

This is something we might want to think about because there are other places where similar extension methods would be useful (get class motion, get class description, etc, etc).

**Comment by norrismiv** [comment]
@baughj the cost of reflection, in this case, should be negligible.

**Comment by kojasou** [comment]
I generally try to avoid reflection during runtime. I'll leave the decision up to you guys.

**Comment by kojasou** [comment]
ok, updated `GetMaxLevelByClass` to use reflection

**Comment by baughj** [comment]
👍 
(sidenote: reflection is indeed 10000% or more slower, but 10,000 iterations takes 7ms so....I wouldn't say we should worry about it)

**Pull request merged**
