### PR TITLE
Adding getting started guide for developers

### PR DESCRIPTION
**Pull request by luke-segars**
Hi all,

I found Hybrasyl to be relatively easy to get going with the exception of the lack of documentation (no particular piece was hard, but *finding* the pieces took some doing). I wrote up a quick getting started guide targeted at developers who might want to help contribute; what do you think about including this as a kickoff point for people who want to get involved? I don't know that everything's worded perfectly just yet and my process might be a bit rough around the edges...let me know if you're interested in including it and I'll polish it up some.

Content-related comments welcome too! Thanks.

### CODE REVIEW

**Comment by baughj** [comment]
This is great, we are definitely interested and will add this to the project. There is also the capacity to make an NSIS installer for the server....I will be providing one soon that is signed for download here and elsewhere, so maybe that will also simplify things a bit.

In terms of the content I mentioned my concerns in #1, I think the dev guide should however point to a seed file to add a few test objects to the database.

**Comment by luke-segars** [comment]
Awesome! An installer would be great though I think a developers guide will
always be useful for those who want to work on the source.

Per #1, I'd love to add something to this document that would give folks
enough MySQL content to log in and walk around somewhere; that's a killer
milestone! It's probably worth adding a section about how to (a) create
things so the game is aware of them, i.e define them in MySQL, and then (b)
test to make sure the thing can be used in game (via the /* admin flags you
guys have built in our whatever makes sense). Adding a section on creating
a new item and a new warp between maps would be a great starting point.

If you can help me get started on #1 I'm happy to take a first crack at the
items above from the perspective of someone new to the project :-)

**Comment by baughj** [comment]
OK, I've committed a seed SQL file (in 21ec0c3b77d08827cb94bcb8489770c12a37fd4d)to create a few test items and two maps, along with warps between them. The following directories need to exist (these are created by the installer automatically):

`My Documents\Hybrasyl`
`My Documents\Hybrasyl\maps`

You'll need `lod500.map` and `lod136.map` from the client to be present there. Load the seed file, put the maps files in the maps directory, and you should be able to login.

**Comment by luke-segars** [comment]
Alright, made another pass and README-ified it! What do you think, @baughj?

**Comment by baughj** [comment]
Can you rebase this against master?

**Comment by baughj** [comment]
Nevermind, I'll stop being a friggin noob over here. Merged, thanks!

**Pull request merged**
