### PR TITLE
Added some stuff

### PR DESCRIPTION
**Pull request by wren11**
“I have read and agree to the terms of the Contributor Agreement
published at
https://github.com/hybrasyl/server/blob/master/CONTRIBUTING.md .”

Added the Following:

 - Default Space bar Attack
 - HP Bar displayed when a target is damaged.
 - Added 2 methods to Map.cs:

     1: public WorldObject GetWorldObjectAt(int x, int y)

     2: public WorldObject GetInfront(User player, int tileCount = 1)

### CODE REVIEW

**Comment by wren11** [comment]
First time with git, Hopefully i did this correctly

**Comment by baughj** [comment]
It looks like your git line feed settings are messed up (note all the changes that are essentially the same text). What is the setting of core.autocrlf in git and/or what are you using to check in the files?

**Comment by baughj** [comment]
Some good stuff here - let's get the line endings fixed and then we can talk about the rest. In particular - thanks for adding the different messages for increasing attributes, that's a nice touch.

**Comment by wren11** [comment]
I think that CRLF line encodings in Visual Studio might of caused it but not sure.
I'm using github on windows, default settings

**Comment by kojasou** [comment]
In regards to the Attack function, I believe @baughj and @Fluffguck wanted spacebar to function the same way as DA (i.e. using each assail skill.) I'm personally of the opinion that assail skills are silly and redundant and should be replaced with just a basic attack function as is in this PR, but I can understand how that might be a bit of a larger deviation from DA than desired.

**Comment by Fluffguck** [comment]
Functionally, from a user's perspective, a few  things have to be true of assail and it's interaction with space bar: learning new assail skills must, by default, increase your melee power, pressing space bar by itself must improve these skills at their own individual rates (ie, leveling from 0/100 to 1/100), and the individual level of each assail skill must be factored into assail damage(chance to hit instead, maybe, in usda?). If these criteria can be cleanly met, I am ok with however it works.

**Comment by Fluffguck** [comment]
God damned autocorrect

**Comment by wren11** [comment]
No worries, I will contribute again will i get some things finished.

**Comment by baughj** [comment]
For the record - this PR makes sweeping changes to Hybrasyl's game systems, is absolutely enormous, and hasn't been discussed or proposed at all on the devel list (as if Python scripting was an afterthought or it was added because we couldn't implement C# scripting - vs an actual design decision). 

This is not the way to submit PRs that you expect to be received well.

**Pull request closed without merging**
