### PR TITLE
Create Beggar.xml

### PR DESCRIPTION
**Pull request by blueowlstudio**
Used in ExampleVillage.xml

## Description
Update the example XMLs so that new contributors will be able to start off more quickly.

## Related PRs
Update to ExampleVillage.xml

branch | PR
------ | ------
ExampleVillage.xml | [link](https://github.com/hybrasyl/server/compare/develop...blueowlstudio:patch-4?expand=1)

## Checklist
- [x] Tested and working locally
- [ ] Reviewed
- [ ] Tested and working on dev server
- [ ] Deployed to staging

## How to QA
Log in, proceed to coord (X="67" Y="16") in ExampleVillage. Beggar NPC visable.

## Impacted Areas in Hybrasyl
-Examples folder

### CODE REVIEW

**Comment by norrismiv** [comment]
Example files are to be just that, examples. Named npc data should not exist here.

**Comment by blueowlstudio** [comment]
Shouldn't there be at least one NPC xml for show? Otherwise the ExampleInn or ExampleVillage maps will not contain any. Given that the ExampleInn / Village xmls contained data for displaying the NPC, I had though that the intention was to show at least something.

**Comment by norrismiv** [comment]
The file itself is fine, just the naming itself should be changed.

**Comment by baughj** [comment]
Please make all of these one PR, as opposed to six...?

I have no opinion on naming.

**Comment by blueowlstudio** [comment]
Re: Norrismiv: Ah, I understand now. Will do so.
Re: baughj: Sure thing on making them one PR.

**Comment by blueowlstudio** [comment]
Will create single pull request with all XML changes.

**Pull request closed without merging**
